"""
DreamCarHunt™ Cloudflare D1 Synchronization Pipeline
VasileDev Group - Automated Arbitrage Database Sync
Pushes scanned Scandinavian vehicles, PR codes, and matches into Cloudflare D1 SQLite.
"""

import json
import logging
import os
import subprocess
import sys
from pathlib import Path

if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

from scrapers.nordic_collector import NordicCollector
from scrapers.pr_decoder import PR_CATALOG

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("SyncToD1")

DB_NAME = "dreamcarhunt-db"
PROJECT_DIR = Path(__file__).resolve().parent.parent


def escape_sql_str(val: str) -> str:
    """Safely escape single quotes for SQLite string literals."""
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def generate_sync_sql(cars) -> str:
    """Generates an idempotent SQL batch script to sync PR codes and cars into D1."""
    statements = []
    statements.append("-- ==========================================================================")
    statements.append("-- BATCH SYNC TO CLOUDFLARE D1 (SQLITE)")
    statements.append("-- Generated by DreamCarHunt™ Nordic Sync Pipeline")
    statements.append("-- ==========================================================\n")

    # 1. Ensure all PR codes from PR_CATALOG exist
    statements.append("-- 1. PR CODES CATALOG")
    for code, info in PR_CATALOG.items():
        statements.append(
            f"INSERT OR IGNORE INTO pr_codes (code, brand, category, name_en, name_ro, name_it, rarity_tier) VALUES ("
            f"{escape_sql_str(code)}, "
            f"{escape_sql_str(info['brand'])}, "
            f"{escape_sql_str(info['category'])}, "
            f"{escape_sql_str(info['name_en'])}, "
            f"{escape_sql_str(info['name_ro'])}, "
            f"{escape_sql_str(info['name_it'])}, "
            f"{escape_sql_str(info['rarity_tier'])}"
            f");"
        )

    statements.append("\n-- 2. VEHICLES (CARS)")
    for c in cars:
        photos = json.dumps([c.image_url])
        pr_codes_json = json.dumps(c.pr_codes)

        # Upsert vehicle into cars
        statements.append(
            f"INSERT INTO cars (vin, registration_plate, make, model, trim, year, mileage_km, "
            f"engine_fuel, power_hp, transmission, price_sek, price_eur, local_market_eur, "
            f"arbitrage_savings_eur, source_portal, source_url, dealer_name, city, country, "
            f"photos_json, pr_codes_json, is_featured) "
            f"VALUES ("
            f"{escape_sql_str(c.vin)}, "
            f"{escape_sql_str(c.reg_nr)}, "
            f"{escape_sql_str(c.make)}, "
            f"{escape_sql_str(c.model)}, "
            f"{escape_sql_str(c.trim)}, "
            f"{c.year}, "
            f"{c.mileage_km}, "
            f"{escape_sql_str(c.fuel_type)}, "
            f"{c.power_hp}, "
            f"{escape_sql_str(c.transmission)}, "
            f"{c.price_sek}, "
            f"{c.price_eur}, "
            f"{c.market_benchmark_eur}, "
            f"{c.arbitrage_savings_eur}, "
            f"'Bytbil / Blocket SE', "
            f"{escape_sql_str(c.listing_url)}, "
            f"{escape_sql_str(c.dealer_name)}, "
            f"{escape_sql_str(c.city)}, "
            f"'SE', "
            f"{escape_sql_str(photos)}, "
            f"{escape_sql_str(pr_codes_json)}, "
            f"{1 if c.is_holy_grail else 0}"
            f") "
            f"ON CONFLICT(vin) DO UPDATE SET "
            f"price_sek=excluded.price_sek, "
            f"price_eur=excluded.price_eur, "
            f"local_market_eur=excluded.local_market_eur, "
            f"arbitrage_savings_eur=excluded.arbitrage_savings_eur, "
            f"pr_codes_json=excluded.pr_codes_json, "
            f"updated_at=CURRENT_TIMESTAMP;"
        )

    # 3. Associate car_pr_matches using subqueries on VIN
    statements.append("\n-- 3. CAR TO PR CODE RELATIONAL MATCHES")
    for c in cars:
        if not c.vin:
            continue
        for pr in c.pr_codes:
            statements.append(
                f"INSERT OR IGNORE INTO car_pr_matches (car_id, pr_code) "
                f"SELECT id, {escape_sql_str(pr)} FROM cars WHERE vin = {escape_sql_str(c.vin)};"
            )

    return "\n".join(statements)


def run_wrangler_d1(sql_file_path: Path) -> bool:
    """Executes an SQL file on Cloudflare D1 via wrangler CLI."""
    cmd = f"cmd.exe /c npx wrangler d1 execute {DB_NAME} --file=\"{sql_file_path}\" --remote"
    logger.info(f"Executing D1 sync command: {cmd}")
    try:
        res = subprocess.run(
            cmd,
            shell=True,
            cwd=str(PROJECT_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            timeout=60
        )
        if res.returncode == 0:
            logger.info("D1 batch execution succeeded!")
            print(res.stdout)
            return True
        else:
            logger.error(f"D1 execution failed with code {res.returncode}:")
            print(res.stderr)
            print(res.stdout)
            return False
    except Exception as e:
        logger.exception(f"Error executing wrangler: {e}")
        return False


def main():
    logger.info("Starting DreamCarHunt™ Nordic Sync Pipeline to Cloudflare D1...")
    collector = NordicCollector()
    unicorns = collector.get_curated_seed_unicorns()
    logger.info(f"Loaded {len(unicorns)} high-yield Scandinavian factory unicorns.")

    sql_content = generate_sync_sql(unicorns)
    temp_sql = PROJECT_DIR / "temp_sync.sql"
    temp_sql.write_text(sql_content, encoding="utf-8")
    logger.info(f"Generated sync SQL script ({len(sql_content)} bytes) at {temp_sql}")

    success = run_wrangler_d1(temp_sql)
    if temp_sql.exists():
        temp_sql.unlink()

    if success:
        logger.info("Verification: Fetching car inventory from D1...")
        verify_cmd = f"cmd.exe /c npx wrangler d1 execute {DB_NAME} --command=\"SELECT id, make, model, year, price_eur, arbitrage_savings_eur, pr_codes_json FROM cars ORDER BY arbitrage_savings_eur DESC;\" --remote"
        res = subprocess.run(verify_cmd, shell=True, cwd=str(PROJECT_DIR), stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, encoding="utf-8")
        print("\n=== CLOUDFLARE D1 LIVE INVENTORY ===")
        print(res.stdout)


if __name__ == "__main__":
    main()
